// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    jQuery("form[role='search'] input[type='text']").attr('placeholder', 'Search for it!');
    return jQuery("form[role='search'] input[type='submit']").hide();
  });

}).call(this);
